language: rust
dist: bionic

os:
#- linux
#- osx
- windows

rust:
  - stable

jobs:
  allow_failures:
    - os: windows

#install:
#  - rustup component add rustfmt
#  - rustfmt -V

script:
  - cargo buid --verbose
#  - cargo fmt --all -- --check
#  - cargo test --manifest-path=librocksdb-sys/Cargo.toml --verbose
