language: rust
dist: bionic
sudo: false

os:
  - linux
  - osx
  - windows

rust:
  - stable

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++

cache: cargo

install:
  - rustup component add rustfmt
  - rustfmt -V

script:
  - cargo fmt --all -- --check
  - cargo test --manifest-path=librocksdb-sys/Cargo.toml
  - cargo test
