language: rust
dist: bionic

os:
#- linux
#- osx
- windows

rust:
  - stable

jobs:
  allow_failures:
    - os: windows

before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        set VS140COMNTOOLS=
        ;;
    esac

#install:
#  - rustup component add rustfmt
#  - rustfmt -V

script:
  - cargo build --verbose
#  - cargo fmt --all -- --check
#  - cargo test --manifest-path=librocksdb-sys/Cargo.toml --verbose
