name: Windows build

on: [push, pull_request]

jobs:
  build:
    runs-on:
      - windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: choco install llvm -y
      - name: Run librocksdb-sys tests
        run: cargo test --manifest-path=librocksdb-sys/Cargo.toml
      - name: Run rocksdb tests
        run: cargo test
